# Generated by Django 3.0.7 on 2020-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0002_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='books', max_length=40),
        ),
    ]
