# Generated by Django 3.0.7 on 2020-07-14 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodapp', '0003_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bookcomment', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
