# Generated by Django 3.0.7 on 2020-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0004_bookcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='product',
            field=models.CharField(default='gh', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='user',
            field=models.CharField(default='samir', max_length=20),
        ),
    ]
