# Generated by Django 3.0.7 on 2020-07-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0007_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularpost_name', models.CharField(max_length=20)),
                ('popularpost_des', models.CharField(max_length=500)),
                ('popularpost_author', models.CharField(max_length=20)),
                ('popularpost_date', models.DateField()),
                ('popularpost_image', models.ImageField(default='', upload_to='goodapp/images')),
                ('popularpost_category', models.CharField(default='books', max_length=40)),
            ],
        ),
    ]
