# Generated by Django 3.0.7 on 2020-07-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0008_popularpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30)),
                ('author_books', models.CharField(max_length=50)),
                ('author_image', models.ImageField(default='', upload_to='goodapp/images')),
                ('author_dec', models.CharField(max_length=10000)),
            ],
        ),
    ]
