# Generated by Django 3.0.7 on 2020-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0010_sahitya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahitya',
            name='sahity_information',
            field=models.CharField(default='-', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sahitya',
            name='sahity_wiki',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='sahitya',
            name='sahitya_Genre',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='sahitya',
            name='sahitya_work_title',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
